package demo.d6.perinta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d6.perinta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.16 16:39:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KotkaTest {



  // Generated by ComTest BEGIN
  /** testKotka9 */
  @Test
  public void testKotka9() {    // Kotka: 9
    Kotka martti = new Kotka("Martti", 800); 
    assertEquals("From: Kotka line: 11", "Martti 800.0", martti.toString()); 
  } // Generated by ComTest END
}