package demo.d8.test;
// Generated by ComTest BEGIN
import demo.d7.Taulukot;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d8.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.31 11:27:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MakihyppyTest {



  // Generated by ComTest BEGIN
  /** testGetTulos34 */
  @Test
  public void testGetTulos34() {    // Makihyppy: 34
    double[] tuomarit = { 0.0, -3.5, 3.5, -6.5, 6.5, 9 } ; 
    assertEquals("From: Makihyppy line: 36", 6.5, Taulukot.summaHuonoinJaParasPois(tuomarit), 0.000001); 
    double[] tuomarit2 = { 0.0, -103.5, 300.5, -605.5, 896.5, 199.5 } ; 
    assertEquals("From: Makihyppy line: 38", 396.5, Taulukot.summaHuonoinJaParasPois(tuomarit2), 0.000001); 
    double[] tuomarit3 = { 0.0, 0, 0, 0, 0, 0 } ; 
    assertEquals("From: Makihyppy line: 40", 0, Taulukot.summaHuonoinJaParasPois(tuomarit3), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulos105 */
  @Test
  public void testTulos105() {    // Makihyppy: 105
    Makihyppy.Tulos tulos = new Makihyppy.Tulos(); 
    assertEquals("From: Makihyppy line: 107", 0, tulos.getPituus(1), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetPituus123 */
  @Test
  public void testSetPituus123() {    // Makihyppy: 123
    Makihyppy.Tulos tulos = new Makihyppy.Tulos(); 
    tulos.setPituus(1, 102.5); 
    assertEquals("From: Makihyppy line: 126", 102.5, tulos.getPituus(1), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPituus142 */
  @Test
  public void testGetPituus142() {    // Makihyppy: 142
    Makihyppy.Tulos tulos = new Makihyppy.Tulos(); 
    tulos.setPituus(2, 85.5); 
    assertEquals("From: Makihyppy line: 145", 85.5, tulos.getPituus(2), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTulos161 */
  @Test
  public void testGetTulos161() {    // Makihyppy: 161
    Makihyppy.Tulos tulos = new Makihyppy.Tulos(); 
    tulos.setPituus(1, 105.5); 
    tulos.setTuomari(1, 1, 20.0); 
    tulos.setTuomari(1, 2, 18.5); 
    tulos.setTuomari(1, 3, 15.5); 
    tulos.setTuomari(1, 4, 19.5); 
    tulos.setTuomari(1, 5, 16.0); 
    assertEquals("From: Makihyppy line: 169", 99.5, tulos.getTulos(0), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetYhteisPisteet187 */
  @Test
  public void testGetYhteisPisteet187() {    // Makihyppy: 187
    Makihyppy.Tulos tulos = new Makihyppy.Tulos(); 
    tulos.setPituus(1, 105.5); 
    tulos.setPituus(2, 104); 
    tulos.setTuomari(1, 1, 20.0);  // ei huomioida  
    tulos.setTuomari(1, 2, 18.5); 
    tulos.setTuomari(1, 3, 15.5);  // ei huomioida
    tulos.setTuomari(1, 4, 19.5); 
    tulos.setTuomari(1, 5, 16.0); 
    tulos.setTuomari(2, 1, 19.5);  // ei huomioida
    tulos.setTuomari(2, 2, 18.5); 
    tulos.setTuomari(2, 3, 15.5); 
    tulos.setTuomari(2, 4, 13);  // ei huomioida
    tulos.setTuomari(2, 5, 16.0); 
    assertEquals("From: Makihyppy line: 201", 193.5, tulos.getYhteisPisteet(), 0.000001); 
  } // Generated by ComTest END
}