package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Postimaksu.*;
import demo.d8.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.01 11:01:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PostimaksuTest {



  // Generated by ComTest BEGIN
  /** testPostimaksu234 */
  @Test
  public void testPostimaksu234() {    // Postimaksu: 34
    double[][] postimaksu = { { 1.00, 1.40, 2.00, 4.00, 6.00, 10.00 } ,{ 50, 100, 250, 500, 1000, 2000 } } ; 
    assertEquals("From: Postimaksu line: 36", 10.0, postimaksu2(postimaksu, 2000), 0.000001); 
    assertEquals("From: Postimaksu line: 37", 2.0, postimaksu2(postimaksu, 140), 0.000001); 
    assertEquals("From: Postimaksu line: 38", 0, postimaksu2(postimaksu, -800), 0.000001); 
    assertEquals("From: Postimaksu line: 39", 6.0, postimaksu2(postimaksu, 756), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHinta79 */
  @Test
  public void testHinta79() {    // Postimaksu: 79
    Postimaksu.Hinta edullinen = new Postimaksu.Hinta(1000, 0.20); 
    assertEquals("From: Postimaksu line: 81", 1000, edullinen.getPaino()); 
    assertEquals("From: Postimaksu line: 82", 0.20, edullinen.getHinta(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetHinta104 */
  @Test
  public void testGetHinta104() {    // Postimaksu: 104
    Postimaksu.Hinta edullinen = new Postimaksu.Hinta(1000, -0.20); 
    assertEquals("From: Postimaksu line: 106", 1000, edullinen.getPaino()); 
    assertEquals("From: Postimaksu line: 107", 0, edullinen.getHinta(), 0.000001); 
    Postimaksu.Hinta suuri = new Postimaksu.Hinta(1000, 2500); 
    assertEquals("From: Postimaksu line: 109", 1000, suuri.getPaino()); 
    assertEquals("From: Postimaksu line: 110", 2500.00, suuri.getHinta(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPainoIf124 */
  @Test
  public void testSuurinKirjeenPainoIf124() {    // Postimaksu: 124
    assertEquals("From: Postimaksu line: 125", 0, suurinKirjeenPainoIf(0)); 
    assertEquals("From: Postimaksu line: 126", 0, suurinKirjeenPainoIf(-6)); 
    assertEquals("From: Postimaksu line: 127", 100, suurinKirjeenPainoIf(1.29)); 
    assertEquals("From: Postimaksu line: 128", 250, suurinKirjeenPainoIf(1.3)); 
    assertEquals("From: Postimaksu line: 129", 250, suurinKirjeenPainoIf(1.31)); 
    assertEquals("From: Postimaksu line: 130", 2000, suurinKirjeenPainoIf(15)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPostimaksu148 
   * @throws EiJaksaKantaaException when error
   */
  @Test
  public void testPostimaksu148() throws EiJaksaKantaaException {    // Postimaksu: 148
    assertEquals("From: Postimaksu line: 150", 0, postimaksu(-70), 0.000001); 
    assertEquals("From: Postimaksu line: 151", 0, postimaksu(0), 0.000001); 
    assertEquals("From: Postimaksu line: 152", 0.6, postimaksu(50), 0.000001); 
    assertEquals("From: Postimaksu line: 153", 0.9, postimaksu(100), 0.000001); 
    assertEquals("From: Postimaksu line: 154", 3.5, postimaksu(999), 0.000001); 
    assertEquals("From: Postimaksu line: 155", 3.5, postimaksu(1000), 0.000001); 
    assertEquals("From: Postimaksu line: 156", 5.5, postimaksu(1001), 0.000001); 
    try {
    postimaksu(3000); 
    fail("Postimaksu: 157 Did not throw EiJaksaKantaaException");
    } catch(EiJaksaKantaaException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}