package demo.d8.test;
// Generated by ComTest BEGIN
import java.util.Calendar;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d8.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.01 09:46:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testPvm109 */
  @Test
  public void testPvm109() {    // Pvm: 109
    Calendar nyt = Calendar.getInstance(); 
    int pv = nyt.get(Calendar.DATE); 
    int kk = nyt.get(Calendar.MONTH) - Calendar.JANUARY + 1; 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm; 
    pvm = new Pvm(1, 1); assertEquals("From: Pvm line: 120", "1.1."+vv, pvm.toString());  
    pvm = new Pvm(1); assertEquals("From: Pvm line: 121", 1+"."+kk+"."+vv, pvm.toString());  
    pvm = new Pvm(); assertEquals("From: Pvm line: 122", pv+"."+kk+"."+vv, pvm.toString());  
    pvm = new Pvm(1, 3, 97); assertEquals("From: Pvm line: 123", "1.3.1997", pvm.toString());  
    pvm = new Pvm("1.5"); assertEquals("From: Pvm line: 124", "1.5."+vv, pvm.toString());  
    pvm = new Pvm("1..1990"); assertEquals("From: Pvm line: 125", "1."+kk+".1990", pvm.toString());  
    pvm = new Pvm("..1990"); assertEquals("From: Pvm line: 126", pv+"."+kk+".1990", pvm.toString());  
  } // Generated by ComTest END
}