package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Taulukot2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.31 20:19:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class Taulukot2Test {


  // Generated by ComTest BEGIN
  /** testSumma24 */
  @Test
  public void testSumma24() {    // Taulukot2: 24
    double[][] taulu1 = { { 1.1, 1.2, 1.3 } , { -1.1, -1.2, -1.3 } } ; 
    double[][] taulu2 = { { 0.1, 0.2, 0.7, 0.8, 0.9 } , { 100.5, 200.5, 300.5 } } ; 
    double[][] taulu3 = { { 4.5, 6.7, 8.9 } , { 10.11, 12.13, 14.15 } } ; 
    assertEquals("From: Taulukot2 line: 28", 0, summa(taulu1), 0.000001); 
    assertEquals("From: Taulukot2 line: 29", 604.2, summa(taulu2), 0.000001); 
    assertEquals("From: Taulukot2 line: 30", 56.49, summa(taulu3), 0.000001); 
  } // Generated by ComTest END
}