package demo.d6.test;
// Generated by ComTest BEGIN
import demo.d5.Astia;
import fi.jyu.mit.ohj2.Suuntaaja;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.23 20:35:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AstiaPeliTest {



  // Generated by ComTest BEGIN
  /** testAstiaPeli28 */
  @Test
  public void testAstiaPeli28() {    // AstiaPeli: 28
    AstiaPeli peli = new AstiaPeli(); 
    assertEquals("From: AstiaPeli line: 30", 100.0, peli.etsi("ä").getTilavuus(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAmpari43 */
  @Test
  public void testGetAmpari43() {    // AstiaPeli: 43
    AstiaPeli peli = new AstiaPeli(); 
    assertEquals("From: AstiaPeli line: 45", 100.0, peli.getAmpari().getTilavuus(), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm56 */
  @Test
  public void testGetLkm56() {    // AstiaPeli: 56
    AstiaPeli peli = new AstiaPeli(); 
    assertEquals("From: AstiaPeli line: 58", 1, peli.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaAstia72 */
  @Test
  public void testLisaaAstia72() {    // AstiaPeli: 72
    AstiaPeli peli = new AstiaPeli(); 
    assertEquals("From: AstiaPeli line: 74", 1, peli.getLkm()); 
    peli.lisaaAstia("5", 5); 
    assertEquals("From: AstiaPeli line: 76", 3, peli.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna93 */
  @Test
  public void testAnna93() {    // AstiaPeli: 93
    AstiaPeli peli = new AstiaPeli(); 
    assertEquals("From: AstiaPeli line: 95", "ä", peli.anna(0).getNimi()); 
    peli.lisaaAstia("5",5); 
    assertEquals("From: AstiaPeli line: 97", "5", peli.anna(1).getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi110 */
  @Test
  public void testEtsi110() {    // AstiaPeli: 110
    AstiaPeli peli = new AstiaPeli(); peli.lisaaAstia("5",5); peli.lisaaAstia("8",8); 
    assertEquals("From: AstiaPeli line: 112", true, peli.etsi("ä").oletko("ä")); 
    assertEquals("From: AstiaPeli line: 113", true, peli.etsi("Ä").oletko("ä")); 
    assertEquals("From: AstiaPeli line: 114", 5.0, peli.etsi("5").getTilavuus(), 0.000001); 
    assertEquals("From: AstiaPeli line: 115", 8.0, peli.etsi("8").getTilavuus(), 0.000001); 
    assertEquals("From: AstiaPeli line: 116", null, peli.etsi("9")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testNimiOhje130 */
  @Test
  public void testNimiOhje130() {    // AstiaPeli: 130
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    AstiaPeli peli = new AstiaPeli(); peli.lisaaAstia("5",5); peli.lisaaAstia("8",8); 
    peli.nimiOhje("4", "6"); 
    String tulos = "Nimeä ei tunneta: 4 tai 6\n" +
    "Tunnetaan nimet: \n" +
    "ä 5 8 \n"; 
    assertEquals("From: AstiaPeli line: 137", null, so.ero(tulos)); 
    peli.nimiOhje("?", "6"); 
    tulos = "Tunnetaan nimet: \nä 5 8 \n"; 
    assertEquals("From: AstiaPeli line: 140", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulostaOhje158 */
  @Test
  public void testTulostaOhje158() {    // AstiaPeli: 158
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    AstiaPeli peli = new AstiaPeli(); peli.lisaaAstia("5",5); peli.lisaaAstia("8",8); 
    peli.tulostaOhje(); 
    assertEquals("From: AstiaPeli line: 162", null, so.ero("Käytössäsi on 5.0 sekä 8.0 litran astiat ja Ämpäri (100.0 l)\n")); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulostaMaarat184 */
  @Test
  public void testTulostaMaarat184() {    // AstiaPeli: 184
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    String tulos =
    "5.0 litran astiassa on 5.0 litraa  nestettä\n" +
    "8.0 litran astiassa on 3.0 litraa nestettä\n"; 
    AstiaPeli peli = new AstiaPeli(); 
    Astia ampari = peli.getAmpari(); 
    Astia a5 = peli.lisaaAstia("5",5); 
    Astia a8 = peli.lisaaAstia("8",8); 
    ampari.kaada(a8); 
    a8.kaada(a5); 
    peli.tulostaMaarat(); 
    assertEquals("From: AstiaPeli line: 199", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPelaa213 */
  @Test
  public void testPelaa213() {    // AstiaPeli: 213
    Suuntaaja.StringInput si = new Suuntaaja.StringInput(""); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    si.input("ä 8\n8 5\n4 5\n\n"); 
    String tulos =
    "Käytössäsi on 5.0 sekä 8.0 litran astiat ja Ämpari (100.0 l)\n"+
    "5.0 litran astiassa on 0.0 litraa nestettä\n" +
    "8.0 litran astiassa on 0.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"                   +
    "5.0 litran astiassa on 0.0 litraa nestettä\n" +
    "8.0 litran astiassa on 8.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"                   +
    "5.0 litran astiassa on 5.0 litraa nestettä\n" +
    "8.0 litran astiassa on 3.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"                   +
    "Nimeä ei tunneta: 4 tai 5\n"                  +
    "Tunnetaan nimet: \n"                          +
    "ä 5 8 \n"                                     +
    "5.0 litran astiassa on 5.0 litraa nestettä\n" +
    "8.0 litran astiassa on 3.0 litraa nestettä\n" +
    "Mistä kaadetaan ja mihin >"; 
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaaAstia("5",5); 
    peli.lisaaAstia("8",8); 
    peli.tulostaOhje(); 
    peli.pelaa(); 
    assertEquals("From: AstiaPeli line: 242", null, so.ero(tulos)); 
    si.palauta(); so.palauta(); 
  } // Generated by ComTest END
}