package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.16 18:02:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KulkuneuvoTest {



  // Generated by ComTest BEGIN
  /** testKulkuneuvo17 */
  @Test
  public void testKulkuneuvo17() {    // Kulkuneuvo: 17
    Kulkuneuvo kanootti = new Kulkuneuvo(15,2); 
    assertEquals("From: Kulkuneuvo line: 19", "Kulkuneuvon nopeus on 15 km/h ja kyydissä on 2 matkustajaa.", kanootti.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNopeus32 */
  @Test
  public void testGetNopeus32() {    // Kulkuneuvo: 32
    Kulkuneuvo tandem = new Kulkuneuvo(30, 2); 
    assertEquals("From: Kulkuneuvo line: 34", 30, tandem.getNopeus()); 
  } // Generated by ComTest END
}