package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.16 18:45:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LaivaTest {



  // Generated by ComTest BEGIN
  /** testGetPurjeet29 */
  @Test
  public void testGetPurjeet29() {    // Laiva: 29
    Laiva moottoriVene = new Laiva(50, 4, 0); 
    assertEquals("From: Laiva line: 31", "Eipä ole purjelaiva!", moottoriVene.getPurjeet()); 
  } // Generated by ComTest END
}