package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.16 19:01:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LentokoneTest {


  // Generated by ComTest BEGIN
  /** testLentokone17 */
  @Test
  public void testLentokone17() {    // Lentokone: 17
    Lentokone boeing = new Lentokone(300, 200, 9000); 
    assertEquals("From: Lentokone line: 19", 9000, boeing.getLentoKorkeus()); 
    assertEquals("From: Lentokone line: 20", "Kulkuneuvon nopeus on 300 km/h ja kyydissä on 200 matkustajaa.", boeing.toString()); 
  } // Generated by ComTest END
}