package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Merkkijonot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.24 17:10:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijonotTest {



  // Generated by ComTest BEGIN
  /** testOnkoMuitaKirjaimia40 */
  @Test
  public void testOnkoMuitaKirjaimia40() {    // Merkkijonot: 40
    String kissa = "kissa"; 
    String asia = "asssssia"; 
    String b = "b"; 
    String aik  = "AIK"; 
    String kaivinKone = "kaivinkone"; 
    assertEquals("From: Merkkijonot line: 46", true, onkoMuitaKirjaimia(kissa, asia)); 
    assertEquals("From: Merkkijonot line: 47", true, onkoMuitaKirjaimia(kissa, asia)); 
    assertEquals("From: Merkkijonot line: 48", true, onkoMuitaKirjaimia(kissa, b)); 
    assertEquals("From: Merkkijonot line: 49", true, onkoMuitaKirjaimia(kissa, aik)); 
    assertEquals("From: Merkkijonot line: 50", true, onkoMuitaKirjaimia(kissa, kaivinKone)); 
    assertEquals("From: Merkkijonot line: 51", true, onkoMuitaKirjaimia(kissa, "a")); 
    assertEquals("From: Merkkijonot line: 52", false, onkoMuitaKirjaimia(kissa, "asiakas")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testViimeinenKenoViiva72 */
  @Test
  public void testViimeinenKenoViiva72() {    // Merkkijonot: 72
    assertEquals("From: Merkkijonot line: 73", 0, viimeinenKenoViiva("\\test")); 
    assertEquals("From: Merkkijonot line: 74", 4, viimeinenKenoViiva("test\\test")); 
    assertEquals("From: Merkkijonot line: 75", 22, viimeinenKenoViiva("/viivoja\\joka/suuntaan\\")); 
    assertEquals("From: Merkkijonot line: 76", 5, viimeinenKenoViiva("&%\"#!\\")); 
    assertEquals("From: Merkkijonot line: 77", -1, viimeinenKenoViiva("porkkana")); 
    assertEquals("From: Merkkijonot line: 78", 2, viimeinenKenoViiva("\\j\\test\"")); 
    assertEquals("From: Merkkijonot line: 79", 1, viimeinenKenoViiva("\\\\test")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoSama123 */
  @Test
  public void testOnkoSama123() {    // Merkkijonot: 123
    assertEquals("From: Merkkijonot line: 124", true, onkoSama(" matti* ", "Matti Nykänen")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaljonkoMerkkeja145 */
  @Test
  public void testPaljonkoMerkkeja145() {    // Merkkijonot: 145
    assertEquals("From: Merkkijonot line: 146", 14, paljonkoMerkkeja("Kissa istuu puussa")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPalindromi165 */
  @Test
  public void testPalindromi165() {    // Merkkijonot: 165
    assertEquals("From: Merkkijonot line: 166", true, palindromi("saippuakauppias")); 
    assertEquals("From: Merkkijonot line: 167", true, palindromi("saippuakivikauppias")); 
    assertEquals("From: Merkkijonot line: 168", true, palindromi("eye")); 
    assertEquals("From: Merkkijonot line: 169", false, palindromi("ukko")); 
    assertEquals("From: Merkkijonot line: 170", true, palindromi("akka")); 
  } // Generated by ComTest END
}