package demo.d7.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Postimaksu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.23 15:20:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PostimaksuTest {



  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPaino29 */
  @Test
  public void testSuurinKirjeenPaino29() {    // Postimaksu: 29
    assertEquals("From: Postimaksu line: 33", 2000, suurinKirjeenPaino(20.00)); 
    assertEquals("From: Postimaksu line: 34", 2000, suurinKirjeenPaino(10.00)); 
    assertEquals("From: Postimaksu line: 35", 1000, suurinKirjeenPaino(9.99)); 
    assertEquals("From: Postimaksu line: 36", 1000, suurinKirjeenPaino(6.00)); 
    assertEquals("From: Postimaksu line: 37", 500, suurinKirjeenPaino(5.99)); 
    assertEquals("From: Postimaksu line: 38", 250, suurinKirjeenPaino(2.00)); 
    assertEquals("From: Postimaksu line: 39", 0, suurinKirjeenPaino(-1.00)); 
  } // Generated by ComTest END
}