package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Taulukot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.31 10:18:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukotTest {



  // Generated by ComTest BEGIN
  /** testParas22 */
  @Test
  public void testParas22() {    // Taulukot: 22
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 24", 20.0, paras(pisteet), 0.000001); 
    double[] tuomarit2 = { 0.0, -103.5, 300.5, -605.5, 896.5, 199.5 } ; 
    assertEquals("From: Taulukot line: 26", 896.5, paras(tuomarit2), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHuonoin44 */
  @Test
  public void testHuonoin44() {    // Taulukot: 44
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 46", 18.0, huonoin(pisteet), 0.000001); 
    double[] tuomarit2 = { 0.0, -103.5, 300.5, -605.5, 896.5, 199.5 } ; 
    assertEquals("From: Taulukot line: 48", -605.5, huonoin(tuomarit2), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma66 */
  @Test
  public void testSumma66() {    // Taulukot: 66
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 68", 94.5, summa(pisteet), 0.000001); 
    double[] tuomarit2 = { 0.0, -103.5, 300.5, -605.5, 896.5, 199.5 } ; 
    assertEquals("From: Taulukot line: 70", 687.5, summa(tuomarit2), 0.000001); 
    double[] pisteet2 = { 2, 4, 6, 8, 10, 200} ; 
    assertEquals("From: Taulukot line: 72", 230, summa(pisteet2), 0.000001); 
    double[] pisteet3 = { -1 ,  -2, -3, -4,  -11, 0 } ; 
    assertEquals("From: Taulukot line: 74", -21, summa(pisteet3), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaHuonoinJaParasPois91 */
  @Test
  public void testSummaHuonoinJaParasPois91() {    // Taulukot: 91
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 93", 56.5, summaHuonoinJaParasPois(pisteet), 0.000001); 
    double[] tuomarit2 = { 0.0, -103.5, 300.5, -605.5, 896.5, 199.5 } ; 
    assertEquals("From: Taulukot line: 95", 396.5, summaHuonoinJaParasPois(tuomarit2), 0.000001); 
  } // Generated by ComTest END
}