package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Taulukot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.24 10:42:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukotTest {



  // Generated by ComTest BEGIN
  /** testParas22 */
  @Test
  public void testParas22() {    // Taulukot: 22
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 24", 20.0, paras(pisteet), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHuonoin42 */
  @Test
  public void testHuonoin42() {    // Taulukot: 42
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 44", 18.0, huonoin(pisteet), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma62 */
  @Test
  public void testSumma62() {    // Taulukot: 62
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 64", 94.5, summa(pisteet), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaHuonoinJaParasPois81 */
  @Test
  public void testSummaHuonoinJaParasPois81() {    // Taulukot: 81
    double[] pisteet = { 19,18,19.5,18,20 } ; 
    assertEquals("From: Taulukot line: 83", 56.5, summaHuonoinJaParasPois(pisteet), 0.000001); 
  } // Generated by ComTest END
}