package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d9.MerkkiJono.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.06 15:00:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkiJonoTest {



  // Generated by ComTest BEGIN
  /** testPisinNouseva16 */
  @Test
  public void testPisinNouseva16() {    // MerkkiJono: 16
    assertEquals("From: MerkkiJono line: 17", 2, pisinNouseva("ei")); 
    assertEquals("From: MerkkiJono line: 18", 2, pisinNouseva("yö")); 
    assertEquals("From: MerkkiJono line: 19", 5, pisinNouseva("uuuuu")); 
    assertEquals("From: MerkkiJono line: 20", 2, pisinNouseva("yök")); 
    assertEquals("From: MerkkiJono line: 21", 1, pisinNouseva("poli")); 
    assertEquals("From: MerkkiJono line: 22", 2, pisinNouseva("ääk")); 
    assertEquals("From: MerkkiJono line: 23", 3, pisinNouseva("maatiainen")); 
    assertEquals("From: MerkkiJono line: 24", 2, pisinNouseva("äyskäri")); 
    assertEquals("From: MerkkiJono line: 25", 3, pisinNouseva("saapas")); 
    assertEquals("From: MerkkiJono line: 26", 7, pisinNouseva("ademopu")); 
    assertEquals("From: MerkkiJono line: 27", 4, pisinNouseva("aamu")); 
    assertEquals("From: MerkkiJono line: 28", 1, pisinNouseva("a")); 
    assertEquals("From: MerkkiJono line: 29", 0, pisinNouseva("")); 
  } // Generated by ComTest END
}