package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.Demo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.04 14:15:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class DemoTest {



  // Generated by ComTest BEGIN
  /** testDemohyvitys19 */
  @Test
  public void testDemohyvitys19() {    // Demo: 19
    assertEquals("From: Demo line: 20", 0, demohyvitys(1, 60)); 
    assertEquals("From: Demo line: 21", 5, demohyvitys(50, 60)); 
    assertEquals("From: Demo line: 22", 6, demohyvitys(66, 60)); 
    assertEquals("From: Demo line: 23", 0, demohyvitys(60, 1)); 
    assertEquals("From: Demo line: 24", 4, demohyvitys(44, 60)); 
  } // Generated by ComTest END
}