package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d4.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.03 19:10:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {


  // Generated by ComTest BEGIN
  /** testHenkilo7 */
  @Test
  public void testHenkilo7() {    // Henkilo: 7
    Henkilo maija = new Henkilo("Maija", "Mehiläinen", 2021); 
    assertEquals("From: Henkilo line: 9", "Maija|Mehiläinen|2021", maija.toString()); 
    assertEquals("From: Henkilo line: 10", "Maija Mehiläinen", maija.getNimi()); 
    assertEquals("From: Henkilo line: 11", 2021, maija.getSyntymavuosi()); 
  } // Generated by ComTest END
}