package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.Tarkkuus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.04 09:44:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TarkkuusTest {



  // Generated by ComTest BEGIN
  /** testEtumerkki15 */
  @Test
  public void testEtumerkki15() {    // Tarkkuus: 15
    assertEquals("From: Tarkkuus line: 16", 0, etumerkki(37-36.8, 0.3)); 
    assertEquals("From: Tarkkuus line: 17", 1, etumerkki(37-36.8, 0.1)); 
    assertEquals("From: Tarkkuus line: 18", 0, etumerkki(37-36.8, 0.2)); 
    assertEquals("From: Tarkkuus line: 19", -1, etumerkki(36.8-37, 0.2)); 
  } // Generated by ComTest END
}