package demo.d5.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.10 14:55:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietokoneTest {



  // Generated by ComTest BEGIN
  /** testGetMuisti64 */
  @Test
  public void testGetMuisti64() {    // Tietokone: 64
    Tietokone macbookAir = new Tietokone(8, 256); 
    assertEquals("From: Tietokone line: 66", 8, macbookAir.getMuisti()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTyyppi76 */
  @Test
  public void testGetTyyppi76() {    // Tietokone: 76
    Tietokone macbookAir = new Tietokone(); 
    assertEquals("From: Tietokone line: 78", "", macbookAir.getTyyppi()); 
  } // Generated by ComTest END
}